version: '3.8'

services:
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  starburger_gunicorn:
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env.dev
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  media_volume: null
  postgres_data: null
  static_volume: null
