version: '3.8'

services:
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    ports:
      - "666:5432"
    env_file:
      - ./.env.prod

  django:
    restart: always
    volumes:
      - ./media:/app/media
      - static_volume:/app/staticfiles
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8080
    container_name: django
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.backend
    env_file:
      - ./.env.prod
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  static_volume: null
  postgres_data: null
