# Generated by Django 3.2 on 2021-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='долгота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления координат')),
            ],
            options={
                'verbose_name': 'место с координатами',
                'verbose_name_plural': 'места с координатами',
            },
        ),
    ]
