# Generated by Django 3.2 on 2021-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoposition', '0002_auto_20211123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='долгота'),
        ),
    ]
