# Generated by Django 3.2 on 2021-11-04 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20211104_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
        ),
    ]
