# Generated by Django 3.2 on 2021-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20211108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('ONLINE', 'Онлайн')], default='ONLINE', max_length=6, verbose_name='способ оплаты'),
        ),
    ]
