# Generated by Django 3.2 on 2021-11-23 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20211123_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('ONLINE', 'Онлайн'), ('UNDEFINED', 'Не указано')], db_index=True, default='UNDEFINED', max_length=9, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
